# Generated by Django 2.2.28 on 2023-05-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('n_questions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.IntegerField()),
                ('player2', models.IntegerField()),
                ('player3', models.IntegerField()),
                ('player4', models.IntegerField()),
                ('player5', models.IntegerField()),
                ('player6', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('n_players', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='q1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q1', to='app.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='q10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q10', to='app.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='q11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q11', to='app.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='q12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q12', to='app.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='q13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q13', to='app.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='q14',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q14', to='app.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='q15',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q15', to='app.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='q2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q2', to='app.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='q3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q3', to='app.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='q4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q4', to='app.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='q5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q5', to='app.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='q6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q6', to='app.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='q7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q7', to='app.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='q8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q8', to='app.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='q9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='q9', to='app.Question'),
        ),
    ]
