# Generated by Django 2.2.28 on 2023-05-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='player2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='player3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='player4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='player5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='player6',
            field=models.IntegerField(null=True),
        ),
    ]
