# Generated by Django 2.2.28 on 2023-05-18 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230515_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.IntegerField()),
                ('player2', models.IntegerField()),
                ('answ1', models.TextField(null=True)),
                ('answ2', models.TextField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Question')),
            ],
        ),
    ]
