# Generated by Django 2.2.28 on 2023-05-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='lobby',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.Lobby'),
            preserve_default=False,
        ),
    ]
