# Generated by Django 2.2.28 on 2023-05-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230519_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='voted',
            field=models.IntegerField(default=0),
        ),
    ]
